
version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies
  save_cache_cmd:
    steps:
      - save_cache:
          key: v1-dependencies
          paths: 
            - my-file.txt
            - circlecireact/node_modules
        

executors:
  docker-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  check-yarn-version:
    executor: docker-executor
    steps:
      - checkout
      - run: yarn --version    
  echo-env:
    executor: docker-executor
    steps:
      - checkout 
      - run: echo $MY_ENV_VAR
  
  install-dependencies:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn install      
      - save_cache_cmd
  
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn build

  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn test


workflows:
  check-yarn-version:
    jobs:
      - check-yarn-version
  echo-env:
    jobs:
      - echo-env:
          context:
            - my-context

  build-and-test:
    jobs:
      - install-dependencies        
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build            
