
version: 2.1

orbs: 
  node: circleci/node@5.0.2

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
  save_cache_cmd:
    steps:
      - save_cache:
          key: v3-dependencies-{{ checksum "package.json" }}
          paths: 
            - my-file.txt
            - node_modules
        

executors:
  docker-executor:
    docker:
      - image: cimg/node:18.4.0

jobs:
  check-yarn-version:
    executor: docker-executor
    steps:
      - checkout
      - run: yarn --version    
  echo-env:
    executor: docker-executor
    steps:
      - checkout 
      - run: echo $MY_ENV_VAR
  
  install-dependencies:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn install      
      - save_cache_cmd
  
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn build
      - persist_to_workspace:
          root: . 
          paths:
            - .next

  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_cmd
      - attach_workspace:
          at: .next
      - run: yarn test


workflows:
  check-yarn-version:
    jobs:
      - check-yarn-version
  echo-env:
    jobs:
      - echo-env:
          context:
            - my-context

  build-and-test-approval:    
    jobs:    
      - request-approval:
          type: approval
          filters: 
            branches:
              only:
                - beta
      - install-dependencies:
          requires:
            - request-approval
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build     

  build-and-test:
    jobs:                    
      - install-dependencies:
          filters: 
            branches:
              ignore:
                - beta            
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build          
  
